import Head from "next/head";
import Image from "next/image";
import { Plus_Jakarta_Sans } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import Hero from "@/components/Hero/Hero";
import About from "@/components/About/About";

const pjs = Plus_Jakarta_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="wrapper">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={pjs.className}>
        <Hero />
        <About />
      </main>
    </div>
  );
}
